Repository HTFML/chinese-poker, pull requests merged in 2020-06, with the labels that each got.

#51 Splash page
  Big2/app.json
  Big2/assets/3-Times-Logos-01.png
  Big2/assets/background.jpg
  Big2/assets/splash.png
Labels: Ready for Review, enhancement

#53 Green felt background
  Big2/assets/greenfelt.jpg
  Big2/src/screens/PlayScreen.js
Labels: Low Priority, Ready for Review

#52 Firebase functions init
  Big2/functions/.eslintrc.json
  Big2/functions/.gitignore
  Big2/functions/index.js
  Big2/functions/package-lock.json
  Big2/functions/package.json
  Big2/package.json
Labels: Architecture, Ready for Review, enhancement

#61 Password2
  Big2/src/navigation/PostAuthStack.js
  Big2/src/screens/ChangeScreen.js
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/SettingsScreen.js
Labels: Ready for Review

#60 Username (displayName) addition
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Lobby.js
  Big2/src/screens/SignUp.js
Labels: Ready for Review

#66 Post game screen
  Big2/src/components/Button.tsx
  Big2/src/navigation/PostAuthStack.js
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Lobby.js
  Big2/src/screens/PlayScreen.js
  Big2/src/screens/PostGameScreen.js
  Big2/yarn.lock
Labels: Architecture, Ready for Review, enhancement

#67 Edit lobby
  Big2/App.js
  Big2/package.json
  Big2/src/screens/Carts.ts
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Lobby.js
  Big2/src/screens/Login.js
  Big2/src/screens/SignUp.js
  Big2/yarn.lock
Labels: Ready for Review
