Repository HTFML/chinese-poker, pull requests merged in 2020-04, with the labels that each got.

#8 edited home page
  Big2/src/components/tabscreens/HomeScreen.js
Labels: Ready for Review

#14 Removed restaurants referencers from app.json
  Big2/app.json
Labels: good first issue

#6 Create rulespage
  Big2/rulespage
Labels: Work In Progress, good first issue

#15 Travis init setup
  .travis.yml
  Big2/__tests__/App-test.js
  Big2/package.json
  Big2/yarn.lock
Labels: enhancement

#19 Build indicator in the README.md
  README.md
Labels: Architecture, enhancement

#28 login and persisting of the respond from firebase through the app
  Big2/src/components/Login.js
  Big2/src/components/tabscreens/HomeScreen.js
Labels: Ready for Review

#30 Lobby Screen
  Big2/App.js
  Big2/package-lock.json
  Big2/package.json
  Big2/rulespage
  Big2/src/components/UserCard.tsx
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Lobby.js
  Big2/src/screens/PlayScreen.js
  Big2/src/screens/Rules.js
  Big2/yarn.lock
  node_modules/.yarn-integrity
  yarn.lock
Labels: Ready for Review
