Repository HTFML/chinese-poker, pull requests merged in 2020-05, with the labels that each got.

#33 Signup functionality
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Login.js
  Big2/src/styles.js
Labels: Ready for Review

#38 Settings
  Big2/App.js
  Big2/android/.gradle/4.10.2/fileChanges/last-build.bin
  Big2/android/.gradle/4.10.2/fileHashes/fileHashes.bin
  Big2/android/.gradle/4.10.2/fileHashes/fileHashes.lock
  Big2/android/.gradle/4.10.2/gc.properties
  Big2/android/.gradle/vcs-1/gc.properties
  Big2/android/.settings/org.eclipse.buildship.core.prefs
  Big2/android/settings.gradle
  Big2/ios/Podfile
  Big2/ios/React_Navigation_Tutorial.xcodeproj/project.pbxproj
  Big2/package-lock.json
  Big2/src/screens/AudioScreen.js
  Big2/src/screens/EnviornementChangeScreen.js
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/PasswordChangeScreen.js
  Big2/src/screens/SettingsScreen.js
  Big2/src/styles.js
  Big2/temple_morning.mp3
  temple_morning.mp3
Labels: High Priority

#37 reusable button
  Big2/src/components/Button.tsx
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Lobby.js
  Big2/src/screens/Login.js
Labels: Architecture, Ready for Review, enhancement

#46 Connect auth user to the firestore database
  Big2/App.js
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Login.js
Labels: Ready for Review

#45 Text input
  Big2/App.js
  Big2/src/components/TextInput.tsx
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Login.js
  Big2/src/utils/Theme.js
  node_modules/.yarn-integrity
  yarn.lock
Labels: Work In Progress

#48 Small edits
  Big2/App.js
  Big2/src/screens/ChangeScreen.js
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/SettingsScreen.js
Labels: Architecture, Ready for Review

#49 Changing config and fixing firestore error
  Big2/App.js
  Big2/package.json
  Big2/src/screens/HomeScreen.js
  Big2/src/screens/Login.js
  Big2/yarn.lock
Labels: Ready for Review
